env:
  global:
    - CODECOV_TOKEN="1544fd51-8c5f-4c02-9f94-dc9be1eb3c74" # https://codecov.io

language: node_js

node_js:
  - 10

before_script:
  - npm install -g codecov

script:
  - npm run coverage # get the coverage run before building
  - codecov          # upload coverage reports to codecov.io
  - npm run build    # we have a build badge, so run the build
